### ISSUE TITLE
Back to top directory NullPointerException:

### ISSUE THREAD

**Issue by cedancp** [MostafaNasiri/AndroidFileChooser#2]
Getting this error when trying to go back when is in the top level

`FATAL EXCEPTION: main
                                                                      Process: com.cedancp.exportwa, PID: 14659
                                                                      java.lang.NullPointerException: Attempt to get length of null array
                                                                          at ir.sohreco.androidfilechooser.FileChooserDialog.loadItems(FileChooserDialog.java:253)
                                                                          at ir.sohreco.androidfilechooser.FileChooserDialog.onClick(FileChooserDialog.java:217)
                                                                          at android.view.View.performClick(View.java:5204)
                                                                          at android.view.View$PerformClick.run(View.java:21153)
                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by MostafaNasiri** [comment]
Weird!
Add this permission to your manifest file and see if it works:
`<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />`

**Comment by cedancp** [comment]
Yes, I have it, its weird, I will see your code this weekend to try and find a solution.
Thanks for answer.

**Comment by MostafaNasiri** [comment]
Thanks. Let me know if you find any problems in the code.
And please run your app on different devices and see if the same exception occurs.

**Comment by cedancp** [comment]
Yes, I was running it on a Huawei p8 lite, it works fine, on Nexus 5 does not work, I will continue with the tests and I let you know.

**Comment by MostafaNasiri** [comment]
Figured it out!
The problem is due to the new permission system which was introduced in android 6 and you have to grant READ_EXTERNAL_STORAGE permission from user before showing the chooser dialog.
I will add a note about this in the README file.
Thanks again.

**Comment by cedancp** [comment]
Hi, I am sorry I was out for some days, I think that's not the problem, I had those permissions granted before opening the chooser dialog. Also, I can navigate through out other directories, the only problem is when I reach the top level.

**Comment by MostafaNasiri** [comment]
You are right my code had a bug and i fixed it in version 1.1.0.

**Comment by cedancp** [comment]
Thanks, the problem is fixed! ... Awesome library by the way, thank you very much
