### ISSUE TITLE
settitle parameters not working

### ISSUE THREAD

**Issue by Jasi2169** [MostafaNasiri/AndroidFileChooser#4]
settitle parameter is not working as expected

**Comment by Jasi2169** [comment]
if i only pass settitle error thrown

```
java.lang.NullPointerException: Attempt to get length of null array
                                                         at z.z.z.FileChooserDialog.loadItems(FileChooserDialog.java:348)
                                                         at z.z.z.FileChooserDialog.onCreateView(FileChooserDialog.java:291)
                                                         at android.support.v4.app.Fragment.performCreateView(Fragment.java:2080)
                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108)
                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
                                                         at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
                                                         at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1677)
                                                         at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:536)
                                                         at android.os.Handler.handleCallback(Handler.java:739)
                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                         at android.os.Looper.loop(Looper.java:158)
                                                         at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by Jasi2169** [comment]
i only selected two parameters
 builder.setTitle("Select a directory:");
        builder.setSelectDirectoryButtonText("Select");
error thrown up,selecting alone settitle also crash app
well i cant see any title either if i set all parameteres

**Comment by Jasi2169** [comment]
i find that only setitle parameter is not working for me

**Comment by MostafaNasiri** [comment]
You mean you can't set the title of the FileChooserDialog? Can you post your code here?

**Comment by Jasi2169** [comment]
yes here it is,as you can see there is no title in dialog

> File f =  new File(Environment.getRootDirectory().getParent().toString());
> 
> ```
>     FileChooserDialog.Builder builder =
>             new FileChooserDialog.Builder(FileChooserDialog.ChooserType.DIRECTORY_CHOOSER, new FileChooserDialog.ChooserListener() {
>                 @Override
>                 public void onSelect(String path) {
> 
>                     Toast.makeText(MainActivity.this,"Jasi this is the file "+path,Toast.LENGTH_LONG).show();
>                 }
>             });
> 
>     builder.setTitle("Select a directory:");
>     builder.setInitialDirectory(f);
>     builder.setSelectDirectoryButtonText("Select SDCard Root Directory");
> 
>     try {
>         builder.build().show(getSupportFragmentManager(), null);
> 
>     } catch (ExternalStorageNotAvailableException e) {
>         e.printStackTrace();
>     }
> ```

**Comment by MostafaNasiri** [comment]
I tested your code in Android 4.1 and Android 6 and there was no problem with dialog's title.

**Comment by Jasi2169** [comment]
i have 6.0.1 and there is no title as "select a directory"

see screenshot

https://s15.postimg.org/r1mzvg9q3/image.png

**Comment by MostafaNasiri** [comment]
Weird! Does this problem only occur when you run your app on Android 6.0.1? Or it happens anyway no matter which version of Android you run your app on?
And please check the solution provided in the link below and see if it works:
http://stackoverflow.com/questions/32405042/android-dialogfragment-title-not-showing

**Comment by Jasi2169** [comment]
did not worked but this is how it worked for me,check it also works for you ?

in style.xml add this

```
<style name="CustomDialog" parent="@style/Theme.AppCompat.Light.Dialog">
<item name="android:windowNoTitle">true</item>             /// no title == true remeber,if i set it false two title are shown
</style>
```

now change your code to
FileChooserDialog.java

```
@Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        getGivenArguments();
        if (title == null) {
            // Remove dialog's title
            // Since setting the style after the fragment is created doesn't have any effect
            // so we have to decide about dialog's title here.
            setStyle(DialogFragment.STYLE_NO_TITLE, 0);
        }else // added line
            setStyle(DialogFragment.STYLE_NORMAL, R.style.CustomDialog); // added line
    }
```
