### ISSUE TITLE
Force close when the dialog is open and you press home button is onpause

### ISSUE THREAD

**Issue by Jasi2169** [MostafaNasiri/AndroidFileChooser#6]
Error is this
```
FATAL EXCEPTION: main
                                                       Process: z.z.z, PID: 13241
                                                       java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = z.z.z.MainActivity$1)
                                                           at android.os.Parcel.writeSerializable(Parcel.java:1468)
                                                           at android.os.Parcel.writeValue(Parcel.java:1416)
                                                           at android.os.Parcel.writeArrayMapInternal(Parcel.java:686)
                                                           at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1330)
                                                           at android.os.Bundle.writeToParcel(Bundle.java:1079)
                                                           at android.os.Parcel.writeBundle(Parcel.java:711)
                                                           at android.support.v4.app.FragmentState.writeToParcel(Fragment.java:144)
                                                           at android.os.Parcel.writeTypedArray(Parcel.java:1254)
                                                           at android.support.v4.app.FragmentManagerState.writeToParcel(FragmentManager.java:398)
                                                           at android.os.Parcel.writeParcelable(Parcel.java:1437)
                                                           at android.os.Parcel.writeValue(Parcel.java:1343)
                                                           at android.os.Parcel.writeArrayMapInternal(Parcel.java:686)
                                                           at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1330)
                                                           at android.os.Bundle.writeToParcel(Bundle.java:1079)
                                                           at android.os.Parcel.writeBundle(Parcel.java:711)
                                                           at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3701)
                                                           at android.app.ActivityThread$StopInfo.run(ActivityThread.java:4622)
                                                           at android.os.Handler.handleCallback(Handler.java:739)
                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                           at android.os.Looper.loop(Looper.java:158)
                                                           at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                           at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
                                                        Caused by: java.io.NotSerializableException: z.z.z.MainActivity
                                                           at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1344)
                                                           at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
                                                           at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
                                                           at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
                                                           at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
                                                           at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
                                                           at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
                                                           at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
                                                           at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
                                                           at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
                                                           at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
                                                           at android.os.Parcel.writeSerializable(Parcel.java:1463)
                                                           at android.os.Parcel.writeValue(Parcel.java:1416) 
                                                           at android.os.Parcel.writeArrayMapInternal(Parcel.java:686) 
                                                           at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1330) 
                                                           at android.os.Bundle.writeToParcel(Bundle.java:1079) 
                                                           at android.os.Parcel.writeBundle(Parcel.java:711) 
                                                           at android.support.v4.app.FragmentState.writeToParcel(Fragment.java:144) 
                                                           at android.os.Parcel.writeTypedArray(Parcel.java:1254) 
                                                           at android.support.v4.app.FragmentManagerState.writeToParcel(FragmentManager.java:398) 
                                                           at android.os.Parcel.writeParcelable(Parcel.java:1437) 
                                                           at android.os.Parcel.writeValue(Parcel.java:1343) 
                                                           at android.os.Parcel.writeArrayMapInternal(Parcel.java:686) 
                                                           at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1330) 
                                                           at android.os.Bundle.writeToParcel(Bundle.java:1079) 
                                                           at android.os.Parcel.writeBundle(Parcel.java:711) 
                                                           at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3701) 
                                                           at android.app.ActivityThread$StopInfo.run(ActivityThread.java:4622) 
                                                           at android.os.Handler.handleCallback(Handler.java:739) 
                                                           at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                           at android.os.Looper.loop(Looper.java:158) 
                                                           at android.app.ActivityThread.main(ActivityThread.java:7224) 
                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                           at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102) 
11-11 23:39:33.503 13508-13508/z.z.z E/ViewRootImpl: sendUserActionEvent() mView == null
```

**Comment by MostafaNasiri** [comment]
I believe this is not related to the library.
